#!/bin/sh
#
# $OpenBSD: xdm,v 1.1 2011/07/07 18:42:17 robert Exp $

daemon="/home/todd/go/bin/btcd"
daemon_flags="-C ~_btc/.btcd/btcd.conf"
daemon_user="_btc"

. /etc/rc.d/rc.subr

pexp="btcd.*btcd.conf"

rc_reload=NO

rc_start() {
	${rcexec} "/usr/bin/time -l ${daemon} ${daemon_flags}" 2>&1 | \
		btclog main $$ &
	renice -n -15 $(pgrep btcd)
}

rc_cmd $1
