#!/bin/sh
#
# $OpenBSD: xdm,v 1.1 2011/07/07 18:42:17 robert Exp $

daemon_user="user1wallet"
daemon="/home/todd/go/bin/btcwallet"
daemon_flags="-C ~${daemon_user}/.btcwallet/btcwallet.conf"

. /etc/rc.d/rc.subr

pexp="btcwallet.*${daemon_user}/.*"

rc_reload=NO

rc_start() {
	${rcexec} "/usr/bin/time -l ${daemon} ${daemon_flags} 2>&1 | btclog mainnet $$ &"
}

rc_cmd $1
